name: Publish Artifacts to Servicenow

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  fetch-latest-tags:
    runs-on: ubuntu-latest
    environment: update_servicenow_artifacts
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Fetch latest tags
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          name: 'John Doe'
          age: 25
